#!/bin/zsh

if ! command -v trivy &> /dev/null
then
    echo "Trivy must be installed for this command to work"
    exit 1
fi

if ! command -v jq &> /dev/null
then
    echo "jq must be installed for this command to work"
    exit 2
fi

OLD_OUT=$(trivy -q i -f json $1 | jq '.Results[]? | .Vulnerabilities[]? | .VulnerabilityID' | sort | uniq)
NEW_OUT=$(trivy -q i -f json $2 | jq '.Results[]? | .Vulnerabilities[]? | .VulnerabilityID' | sort | uniq)

OLD_OUT=("${(@f)OLD_OUT}")
NEW_OUT=("${(@f)NEW_OUT}")

for new_cve_item in $NEW_OUT
    do OLD_OUT=(${OLD_OUT#$new_cve_item})
done

echo "Diff:"
echo "$OLD_OUT"
